const data = {
  products: [
    {
      _id: "1",
      name: "Sport Coat",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: "2",
      name: "Adidas Shoes",
      category: "shoes",
      image: "./images/p2.jpeg",
      price: 99,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: "3",
      name: "Nike Shirt",
      category: "shirts",
      image: "./images/p3.jpeg",
      price: 112,
      brand: "Nike",
      rating: 2.5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: "4",
      name: "Slim Cargo Pants",
      category: "pants",
      image: "./images/p4.jpeg",
      price: 122,
      brand: "Dickis",
      rating: 5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: "5",
      name: "Nike Cosmic Basketball Shoes",
      category: "shoes",
      image: "./images/p5.jpeg",
      price: 125,
      brand: "Nike",
      rating: 1.5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: "6",
      name: "Long Sleeve Shirts",
      category: "shirts",
      image: "./images/p6.jpg",
      price: 89,
      brand: "Twillory",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality product",
    },
  ],
};

export default data;
